"""How many of an organization's refined examples come from a change whose commit names an AI tool.

OpenInfra's AI policy (approved 2025-07-08) asks for `Assisted-By:` or `Generated-By:` trailers on
AI-assisted commits; the same trailers and an agent `Co-Authored-By:` appear elsewhere. The raw
snapshots carry no commit messages, so each trailer is a Gerrit `message:` search, and a refined
example is flagged when its (project, Change-Id) is among the hits. Trailers are voluntary, so
the share is a lower bound on AI-assisted targets, not an estimate of them.

The search is bounded by `mergedbefore:` the test window's start: a change merged before it was
created before it, so no sealed change is requested. A train or dev change merged later is
missed, which also errs low.

    uv run --no-sync --no-active python scripts/ai_trailers.py \\
        --refined openstack=../wm-bots/datasets/gerrit/openstack/refined \\
        --refined wikimedia=../fa-auto/datasets/gerrit/wikimedia/refined \\
        --out datasets/results/ai-trailers.json
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path

from sphragis.corpus.cli import GERRIT, WINDOWS, http_transport
from sphragis.corpus.gerrit import fetch_changes
from sphragis.provenance import provenance_header

# Gerrit's `message:` matches words anywhere ("generated by" in prose), so each search only
# nominates changes; a change counts when its current commit message carries the trailer as a
# line of its own, read with these patterns.
SEARCHES = ('"Assisted-By"', '"Generated-By"', '"Co-Authored-By"')
# A trailer counts when its value names an AI tool or model. Most OpenStack `Generated-By:` lines
# name the community's own scripts (`openstack/releases:tools/...`), which are counted apart as
# tool-generated, not as AI.
AI_NAMES = (
    r"claude|anthropic|copilot|cursor|gemini|codex|chatgpt|openai|gpt-?\d|devin|aider|windsurf"
    r"|codeium|tabnine|openhands|junie|sonnet|opus|qwen|llama|deepseek|kiro|cline|amazon q"
)
TRAILER = re.compile(r"^(Assisted-By|Generated-By|Co-Authored-By):[ \t]*(.*)$", re.I | re.M)
AI_VALUE = re.compile(rf"\b(?:{AI_NAMES})", re.I)
# `owner/repo:path`, a script in one of the community's repositories.
TOOL_VALUE = re.compile(r"^[\w.-]+/[\w.-]+:\S+")


def trailer_kinds(message: str) -> set[str]:
    """The AI trailers a commit message carries, plus `tool` for a scripted `Generated-By`."""
    kinds = set()
    for key, value in TRAILER.findall(message):
        if AI_VALUE.search(value):
            kinds.add(key.title())
        elif key.lower() == "generated-by" and TOOL_VALUE.match(value.strip()):
            kinds.add("tool")
    return kinds


# The earliest window the corpora hold.
SINCE = WINDOWS["pilot"][0]
SEALED_FROM = WINDOWS["test"][0]

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--refined", action="append", required=True, help="org=refined directory")
parser.add_argument("--out", type=Path, required=True)


def window_of(created: str) -> str | None:
    day = created[:10]
    return next((name for name, (lo, hi) in WINDOWS.items() if lo <= day < hi), None)


def main() -> None:
    args = parser.parse_args()
    transport = http_transport()
    report: dict = {
        "searches": list(SEARCHES),
        "ai_names": AI_NAMES,
        "since": SINCE,
        "merged_before": SEALED_FROM,
    }
    report["orgs"] = {}
    for spec in args.refined:
        org, directory = spec.split("=", 1)
        flagged: dict[tuple[str, str], set[str]] = {}
        queries = {}
        for search in SEARCHES:
            query = f"status:merged mergedafter:{SINCE} mergedbefore:{SEALED_FROM} message:{search}"
            changes, record = fetch_changes(
                GERRIT[org],
                query,
                transport=transport,
                options=("CURRENT_REVISION", "CURRENT_COMMIT"),
            )
            verified = 0
            for change in changes:
                revision = change.get("revisions", {}).get(change.get("current_revision"), {})
                message = (revision.get("commit") or {}).get("message", "")
                kinds = trailer_kinds(message)
                if kinds:
                    verified += 1
                    flagged.setdefault((change["project"], change["change_id"]), set()).update(
                        kinds
                    )
            queries[search] = {"nominated": record["count"], "verified": verified}
        examples: Counter[str] = Counter()
        hits: Counter[str] = Counter()
        tool: Counter[str] = Counter()
        ai_changes: dict[str, set[tuple[str, str]]] = {}
        by_trailer: Counter[str] = Counter()
        for path in sorted(Path(directory).glob("*.jsonl")):
            for line in path.open():
                row = json.loads(line)
                window = window_of(str(row["created"]))
                if window is None or window == "test":
                    continue
                examples[window] += 1
                found = flagged.get((row["project"], row["change_id"]), set())
                if found - {"tool"}:
                    hits[window] += 1
                    ai_changes.setdefault(window, set()).add((row["project"], row["change_id"]))
                    by_trailer.update(found - {"tool"})
                elif found:
                    tool[window] += 1
        report["orgs"][org] = {
            "changes_by_search": queries,
            "changes_ai": sum(bool(k - {"tool"}) for k in flagged.values()),
            "changes_tool_generated": sum(k == {"tool"} for k in flagged.values()),
            "examples": dict(examples),
            "examples_flagged": dict(hits),
            "changes_behind_flagged_examples": {w: len(c) for w, c in ai_changes.items()},
            "share_flagged": {w: hits[w] / n for w, n in examples.items() if n},
            "examples_flagged_by_trailer": dict(by_trailer),
            "examples_tool_generated": dict(tool),
        }
        print(org, report["orgs"][org]["examples_flagged"], "of", dict(examples))
    report["provenance"] = provenance_header()
    args.out.write_text(json.dumps(report, indent=2) + "\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
