"""How many of an organization's examples come from a change whose commit names an AI tool.

OpenInfra's AI policy (approved 2025-07-08) asks for `Assisted-By:` or `Generated-By:` trailers on
AI-assisted commits; the same trailers and an agent `Co-Authored-By:` appear elsewhere. The raw
snapshots carry no commit messages, so each trailer is a Gerrit `message:` search, and an example
is flagged when its (project, Change-Id) is among the changes whose merged commit message carries
one. Windows are the corpus's own: refined examples deduplicated and split as the study loads them.

The flag is per change, read from the merged commit message, so it neither bounds nor estimates
AI-assisted targets: trailers are voluntary (undisclosed use is missed), and a trailer added in a
late patch set flags examples from earlier ones. Disclosure itself became policy on OpenStack
inside the training window.

The search is bounded by `mergedbefore:` the test window's start: a change merged before it was
created before it, so no sealed change is requested. Only with `--through-test`, once every
organization's seal records acceptance, does it run through the test window, to the day of the
fetch, and tally that window too.

    uv run --no-sync --no-active python scripts/ai_trailers.py \\
        --root openstack=../wm-bots/datasets/gerrit \\
        --root wikimedia=../fa-auto/datasets/gerrit \\
        --out datasets/results/ai-trailers.json
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter, defaultdict
from collections.abc import Iterable, Mapping
from datetime import UTC, datetime
from pathlib import Path

from sphragis.corpus.cli import GERRIT, http_transport
from sphragis.corpus.gerrit import fetch_changes
from sphragis.corpus.load import refined_examples
from sphragis.corpus.pipeline import run_dedup, run_split
from sphragis.corpus.split import seal_open
from sphragis.corpus.windows import WINDOWS
from sphragis.provenance import provenance_header

# Gerrit's `message:` matches words anywhere ("generated by" in prose), so each search only
# nominates changes; a change counts when its merged commit message carries the trailer as a
# line of its own.
SEARCHES = ('"Assisted-By"', '"Generated-By"', '"Co-Authored-By"')
# Names only an AI tool or model carries, for any trailer.
AI_TOOLS = (
    r"claude|anthropic|copilot|cursor|gemini|codex|chatgpt|openai|gpt-?\d[\w.]*|codeium|tabnine"
    r"|openhands|sonnet|opus|qwen|llama|deepseek|amazonq|amazon q developer|llm"
)
# Tool names that are also personal names: read only where the value names a tool, never in
# `Co-Authored-By`, whose value is a person unless it names a tool above.
AI_TOOLS_ALSO_NAMES = r"devin|junie|cline|kiro|aider|windsurf"
TRAILER = re.compile(r"^[ \t]*(Assisted-By|Generated-By|Co-Authored-By):[ \t]*(.*)$", re.I | re.M)
AI_VALUE = re.compile(rf"\b(?:{AI_TOOLS})\b", re.I)
AI_TOOL_VALUE = re.compile(rf"\b(?:{AI_TOOLS}|{AI_TOOLS_ALSO_NAMES})\b", re.I)
# `owner/repo:path`, a script in one of the community's repositories (most OpenStack
# `Generated-By:` lines), counted apart as tool-generated.
TOOL_VALUE = re.compile(r"^[\w.-]+/[\w.-]+:\S+")
# The earliest window the corpora hold, and the sealed window's start.
SINCE = WINDOWS["pilot"][0]
SEALED_FROM = WINDOWS["test"][0]
READ_WINDOWS = ("pilot", "train", "dev")

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--root", action="append", required=True, help="org=root of a built corpus")
parser.add_argument("--out", type=Path, required=True)
parser.add_argument(
    "--through-test",
    action="store_true",
    help="after acceptance only: search through the test window, up to the day of the fetch",
)


def trailer_kinds(message: str) -> dict[str, list[str]]:
    """The AI trailers a commit message carries, by key, with their values; `tool` for scripts."""
    kinds: dict[str, list[str]] = defaultdict(list)
    for key, value in TRAILER.findall(message):
        key, value = key.title(), value.strip()
        pattern = AI_VALUE if key == "Co-Authored-By" else AI_TOOL_VALUE
        if pattern.search(value):
            kinds[key].append(value)
        elif key == "Generated-By" and TOOL_VALUE.match(value):
            kinds["tool"].append(value)
    return dict(kinds)


def search_query(search: str, merged_before: str = SEALED_FROM) -> str:
    """A merged-change search, by default one that can return no change created in the sealed
    window; `merged_before` later than the seal only once the test window is unsealed."""
    return f"status:merged mergedafter:{SINCE} mergedbefore:{merged_before} message:{search}"


def tally(
    windows: Mapping[str, Iterable[Mapping]],
    flagged: Mapping[tuple[str, str], set[str]],
    read: Iterable[str] = READ_WINDOWS,
) -> dict:
    """Examples and changes per window, and how many carry an AI trailer or a scripted one."""
    out: dict = {}
    for window in read:
        rows = list(windows.get(window, []))
        changes = {(r["project"], r["change_id"]) for r in rows}
        kinds = {key: flagged.get(key, set()) for key in changes}
        ai = {key for key, k in kinds.items() if k - {"tool"}}
        tool = {key for key, k in kinds.items() if k == {"tool"}}
        out[window] = {
            "examples": len(rows),
            "changes": len(changes),
            "examples_ai": sum((r["project"], r["change_id"]) in ai for r in rows),
            "changes_ai": len(ai),
            "examples_tool_generated": sum((r["project"], r["change_id"]) in tool for r in rows),
            "changes_tool_generated": len(tool),
        }
    return out


def main() -> None:
    args = parser.parse_args()
    # The test window is searched only once every organization's seal records acceptance, and
    # then up to the day of the fetch: the registered "read at fetch time for the test window".
    bound = SEALED_FROM
    if args.through_test:
        roots = dict(spec.split("=", 1) for spec in args.root)
        sealed = [org for org, root in roots.items() if not seal_open(Path(root), org)]
        if sealed:
            raise SystemExit(f"--through-test: the test window of {sealed} is still sealed")
        bound = datetime.now(UTC).date().isoformat()
    transport = http_transport()
    report: dict = {
        "searches": list(SEARCHES),
        "ai_tools": AI_TOOLS,
        "ai_tools_also_names": AI_TOOLS_ALSO_NAMES,
        "since": SINCE,
        "merged_before": bound,
        "orgs": {},
    }
    for spec in args.root:
        org, root = spec.split("=", 1)
        flagged: dict[tuple[str, str], set[str]] = {}
        values: Counter[str] = Counter()
        nominated = {}
        for search in SEARCHES:
            changes, record = fetch_changes(
                GERRIT[org],
                search_query(search, bound),
                transport=transport,
                options=("CURRENT_REVISION", "CURRENT_COMMIT"),
            )
            nominated[search] = record["count"]
            for change in changes:
                revision = change.get("revisions", {}).get(change.get("current_revision"), {})
                kinds = trailer_kinds((revision.get("commit") or {}).get("message", ""))
                if kinds:
                    key = (change["project"], change["change_id"])
                    flagged.setdefault(key, set()).update(kinds)
                    # The tool named, never the whole value, which can name a person.
                    values.update(
                        f"{k}: {AI_TOOL_VALUE.search(v).group(0).lower()}"  # type: ignore[union-attr]
                        for k, vs in kinds.items()
                        if k != "tool"
                        for v in vs
                    )
        kept, _ = run_dedup(refined_examples(Path(root), org))
        windows, _, _ = run_split(kept, WINDOWS)
        if windows.get("test") and not args.through_test:
            raise SystemExit(f"{org}: the corpus holds test-window examples; it is sealed")
        report["orgs"][org] = {
            "nominated_by_search": nominated,
            "changes_ai": sorted(f"{p} {c}" for (p, c), k in flagged.items() if k - {"tool"}),
            "changes_tool_generated": sum(k == {"tool"} for k in flagged.values()),
            "ai_trailer_values": dict(values.most_common()),
            "windows": tally(
                windows, flagged, (*READ_WINDOWS, "test") if args.through_test else READ_WINDOWS
            ),
        }
        print(org, report["orgs"][org]["windows"])
    report["provenance"] = provenance_header()
    args.out.write_text(json.dumps(report, indent=2) + "\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
