"""The AI-trailer flag: a trailer line naming an AI tool, not prose or a community script."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
_spec = importlib.util.spec_from_file_location("ai_trailers", ROOT / "scripts" / "ai_trailers.py")
assert _spec is not None and _spec.loader is not None
trailers = importlib.util.module_from_spec(_spec)
sys.argv = ["ai_trailers"]
_spec.loader.exec_module(trailers)


@pytest.mark.parametrize(
    ("message", "kinds"),
    [
        ("Fix x\n\nGenerated-By: claude-code\nChange-Id: I1", {"Generated-By"}),
        ("Fix x\n\nAssisted-by: Cursor (gpt-5)", {"Assisted-By"}),
        ("Fix x\n\nCo-authored-by: Claude <noreply@anthropic.com>", {"Co-Authored-By"}),
        ("Fix x\n\nCo-Authored-By: Jane Doe <jane@example.org>", set()),
        ("This file is generated by tox.\nSee Generated-By: in the docs", set()),
        ("Release x\n\nGenerated-By: openstack/releases:tools/bulk_review.sh", {"tool"}),
        ("Fix x\n\nAssisted-By: JetBrains Junie", {"Assisted-By"}),
    ],
)
def test_a_trailer_counts_only_when_it_names_an_ai_tool(message: str, kinds: set[str]) -> None:
    assert trailers.trailer_kinds(message) == kinds


def test_examples_are_assigned_to_the_window_their_change_was_created_in() -> None:
    assert trailers.window_of("2024-11-03 10:00:00.000000000") == "train"
    assert trailers.window_of("2025-09-30 23:59:59") == "dev"
    assert trailers.window_of(trailers.SEALED_FROM) == "test"
