"""The AI-trailer flag: a trailer line naming an AI tool, not prose, a person or a script."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
_spec = importlib.util.spec_from_file_location("ai_trailers", ROOT / "scripts" / "ai_trailers.py")
assert _spec is not None and _spec.loader is not None
trailers = importlib.util.module_from_spec(_spec)
sys.argv = ["ai_trailers"]
_spec.loader.exec_module(trailers)


@pytest.mark.parametrize(
    ("message", "keys"),
    [
        ("Fix x\n\nGenerated-By: claude-code\nChange-Id: I1", {"Generated-By"}),
        ("Fix x\n\nAssisted-by: Cursor (gpt-5)", {"Assisted-By"}),
        ("Fix x\n\nCo-authored-by: Claude <noreply@anthropic.com>", {"Co-Authored-By"}),
        ("Fix x\n\nAssisted-By: JetBrains Junie", {"Assisted-By"}),
        ("Fix x\n\n  Assisted-By: an LLM", {"Assisted-By"}),
        ("Release x\n\nGenerated-By: openstack/releases:tools/bulk_review.sh", {"tool"}),
        ("Fix x\n\nCo-Authored-By: Jane Doe <jane@example.org>", set()),
        ("Fix x\n\nCo-Authored-By: Devin Smith <d@example.org>", set()),
        ("Fix x\n\nCo-Authored-By: Junie Lee <j@example.org>", set()),
        ("Fix x\n\nCo-Authored-By: Sam Cline <s@example.org>", set()),
        ("Fix x\n\nCo-Authored-By: Paul Devine <p@example.org>", set()),
        ("This file is generated by tox.\nSee Generated-By: in the docs", set()),
    ],
)
def test_a_trailer_counts_only_when_it_names_an_ai_tool(message: str, keys: set[str]) -> None:
    assert set(trailers.trailer_kinds(message)) == keys


def test_every_search_is_bounded_by_the_sealed_window() -> None:
    for search in trailers.SEARCHES:
        query = trailers.search_query(search)
        assert f"mergedbefore:{trailers.WINDOWS['test'][0]}" in query
        assert "status:merged" in query


def test_examples_and_changes_are_counted_by_project_and_change_id() -> None:
    def row(project: str, change: str) -> dict:
        return {"project": project, "change_id": change}

    windows = {
        "dev": [row("a/x", "I1"), row("a/x", "I1"), row("a/y", "I1"), row("a/x", "I2")],
        "train": [row("a/x", "I3")],
    }
    flagged = {("a/x", "I1"): {"Assisted-By"}, ("a/x", "I3"): {"tool"}}
    counted = trailers.tally(windows, flagged)
    assert counted["dev"] == {
        "examples": 4,
        "changes": 3,
        "examples_ai": 2,
        "changes_ai": 1,
        "examples_tool_generated": 0,
        "changes_tool_generated": 0,
    }
    assert counted["train"]["examples_tool_generated"] == 1 and counted["train"]["examples_ai"] == 0
    assert counted["pilot"]["examples"] == 0


def test_the_searches_stop_at_the_seal_unless_told_the_window_is_open() -> None:
    assert f"mergedbefore:{trailers.SEALED_FROM}" in trailers.search_query("Assisted-By")
    assert "mergedbefore:2027-03-01" in trailers.search_query("Assisted-By", "2027-03-01")


def test_searching_through_the_test_window_needs_every_seal_open(tmp_path, monkeypatch) -> None:
    import json
    import sys

    import pytest

    (tmp_path / "openstack").mkdir()
    argv = ["ai_trailers", "--root", f"openstack={tmp_path}", "--out", str(tmp_path / "o.json")]
    monkeypatch.setattr(sys, "argv", [*argv, "--through-test"])
    with pytest.raises(SystemExit, match=r"test window of \['openstack'\] is still sealed"):
        trailers.main()
    (tmp_path / "openstack" / "seal.json").write_text(json.dumps({"accepted_at": "2027-02-01"}))
    monkeypatch.setattr(
        trailers, "http_transport", lambda: (_ for _ in ()).throw(RuntimeError("opened"))
    )
    with pytest.raises(RuntimeError, match="opened"):
        trailers.main()
